### ISSUE TITLE
Any chance to support KTX texture format?

### ISSUE THREAD

**Issue by vpenades** [StbSharp/StbImageSharp#12]
KTX is becoming a popular texture format due to its unique features.... it has a special kind of block encoding that can be decoded to multiple block encoding formats available in varios hardware devices.

For example, KTX can be decoded to formats already found in DDS files, which is exclusive to DirectX hardware, but also to formats available in smart devices like ETC

**Comment by rds1983** [comment]
StbImageSharp will support only formats that are supported by the original stb_image.h
Though there's different port for KTX: https://github.com/rds1983/DdsKtxSharp
