### ISSUE TITLE
No more "StbSharpSafe" for StbImageSharp?

### ISSUE THREAD

**Issue by rickomax** [StbSharp/StbImageSharp#2]
Hi!

I was looking on the old repository and found-out there are the "StbSharpSafe" methods to avoid using "unsafe" calls. 

Is it available for this new repository?

**Comment by rds1983** [comment]
Hello!

Well, StbSharpSafe has only safe version of StbTrueTypeSharp I think. There wasnt safe StbImageSharp ever. And frankly I dont see why it is needed.

**Comment by rickomax** [comment]
> Hello!
> 
> Well, StbSharpSafe has only safe version of StbTrueTypeSharp I think. There wasnt safe StbImageSharp ever. And frankly I dont see why it is needed.

I was planning to use it on a specific project that cannot use unsafe methods.

**Comment by rds1983** [comment]
Closing this case. As there's now dedicated project that would include replacing unsafe StbImageSharp code with safe: https://github.com/StbSharp/StbImageLib
