### ISSUE TITLE
Stackalloc in loop causes stackoverflow.

### ISSUE THREAD

**Issue by NogginBops** [StbSharp/StbImageSharp#21]
In `stbi__hdr_load` the following lines (https://github.com/StbSharp/StbImageSharp/blob/4fe1d6bf253b6c30cdc7f8c8db5a98cad4342453/generation/StbImageSharp.Generator/stb_image.h#L7159C13-L7159C29, and https://github.com/StbSharp/StbImageSharp/blob/4fe1d6bf253b6c30cdc7f8c8db5a98cad4342453/generation/StbImageSharp.Generator/stb_image.h#L7142C13-L7142C13) 
```c
stbi_uc rgbe[4];
```
is translated as
```
var rgbe = stackalloc byte[4];
```

which is almost a one to one translation, the issue however is that C# `stackalloc` will not deallocate when going out of scope, instead it will only deallocate once the entire function returns (`stackalloc` follows `alloca` more than just creating an array in c).

For some inputs this causes a `StackOverflowException` to be thrown.

**Comment by rds1983** [comment]
good catch, thanks

**Comment by NogginBops** [comment]
I've modified my fork to fix these issues and I could make a PR with a fix, but I'm unsure about modifying generated files (though it seems like they have been manually altered so...)

This could also be fixed in .net 8 using `InlineArray` to create stack allocated fixed size arrays that go out of scope in the same way that C arrays would.

**Comment by rds1983** [comment]
I would be grateful for a PR. I would try to transfer those changes if files get regenerated.
